PLANET-6124: Remove target from link. It comes from the React Component
greenpeace/planet4-master-theme pull request #1411
Opened 2021-07-02 15:00 UTC by GP-Dan-Tovbein

https://jira.greenpeace.org/browse/PLANET-6124

Ref: https://jira.greenpeace.org/browse/PLANET-6124

---

2021-07-02 17:54 UTC, planet-4 commented
### Test instance is ready :rocket:

:new_moon: [titan](https://www-dev.greenpeace.org/test-titan)

:watch: 2021.07.02 17:54:00

2021-07-05 08:28 UTC, mleray requested changes
The problem is that this file takes care of all links in the page content, and we still need to add the target and class for links that are not in Columns blocks... I think a solution for this issue would probably be to check if the link has the `call-to-action-link` that is [added](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/1b55e9da077de86c40e70aff03a7d8f2fbf7c8ff/assets/src/blocks/Columns/Columns.js#L78) in the Columns block? From a quick search it seems to be used only there 🤔 I'm just not sure whether we want to keep the external link icon in this case or not, since those links are actually not necessarily external that might be confusing... That should probably be checked with the design team

2021-07-05 11:24 UTC, dantovbein commented
@mleray, thanks for your review! Have you seen also [this](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/624) PR? Because it's related to this current fix.

2021-07-09 13:11 UTC, GP-Dan-Tovbein commented
@mleray I’ve updated the PR. I’ve not added  :not(.call-to-action-link)  since the external icon is not being shown through this way, so, I tackled another method to set target to links.

2021-07-19 07:06 UTC, mleray approved these changes
Looks good to me 👍

2021-07-19 20:33 UTC, merged