PLANET-6803: Add Gravity Forms Capabilities for Editors
greenpeace/planet4-master-theme pull request #1747
Opened 2022-06-27 20:22 UTC by GP-Dan-Tovbein

Ref: https://jira.greenpeace.org/browse/PLANET-6803

### Test
Run `docker-compose exec php-fpm wp p4-run-activator` on your local and check if it's works.

**If you don't have already created a user with an editor role then create it.**

2022-06-28 11:20 UTC, GP-Dan-Tovbein commented on src/Role/GravityForms.php
> +					$role->remove_cap( $capability );
We need to be sure that we won't set undesired capabilities.

2022-06-29 11:06 UTC, lithrel requested changes
a little fix on the missing gravityforms_delete_forms capability

2022-06-29 11:06 UTC, lithrel commented on src/Role/GravityForms.php
> +						'gravityforms_create_form'    => true,
I think it should be `gravityforms_delete_forms` instead of a duplicate of the previous line

2022-06-29 11:06 UTC, lithrel commented on src/Role/GravityForms.php
> +	public static function add_capaibilities_to_user_roles() {
just a typo in _capa**i**bilities_ `add_capaibilities_to_user_roles` to `add_capabilities_to_user_roles`

2022-06-29 11:47 UTC, lithrel approved these changes
:+1:

2022-06-30 12:47 UTC, merged