Implement new Yellow CSS variables to links
greenpeace/planet4-master-theme pull request #2005
Opened 2023-05-04 17:16 UTC by GP-Dan-Tovbein

## Description
As a part of [#1044](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1044) we will need to standardize the yellow color to the Split Two Columns block and to the Campaign Cover block, by using always the `yellow-500` color.

2023-05-05 08:50 UTC, planet-4 commented
### Test instance is ready :rocket:

:new_moon: [rhea](https://www-dev.greenpeace.org/test-rhea) | [admin](https://www-dev.greenpeace.org/test-rhea/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-rhea/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-rhea) | [composer-local.json](https://github.com/greenpeace/planet4-test-rhea/blob/main/composer-local.json)

:watch: 2023.05.05 08:50:51

2023-05-05 09:13 UTC, mleray requested changes
We forgot the [hover styles](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/assets/src/styles/blocks/SplitTwoColumns.scss#L99-L101) for the SplitTwoColumns 😬 They need to be updated with the new identity too, because right now it looks off

2023-05-08 13:58 UTC, GP-Dan-Tovbein commented
> We forgot the [hover styles](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/main/assets/src/styles/blocks/SplitTwoColumns.scss#L99-L101) for the SplitTwoColumns 😬 They need to be updated with the new identity too, because right now it looks off

@mleray FYI, It's now added!

2023-05-09 13:07 UTC, mleray approved these changes
Looks good to me 👍

2023-05-10 06:47 UTC, merged