PLANET-7396: Move Highlighted CTA block pattern into master theme
greenpeace/planet4-master-theme pull request #2259
Opened 2024-04-17 18:41 UTC by GP-Dan-Tovbein

Ref: https://jira.greenpeace.org/browse/PLANET-7396
Related PR: [plugin#1203](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1203)

# Description
Move HighlightedCTA block into the theme

## Testing
- Create a new page
- Edit that page
- Click on "+" and click on "Patterns" tab
- The HighlightedCTA block should be visible on that list

2024-04-18 13:48 UTC, planet-4 commented
### Test instance is ready :rocket:

:new_moon: [pluto](https://www-dev.greenpeace.org/test-pluto) | [admin](https://www-dev.greenpeace.org/test-pluto/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-pluto/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-pluto) | [composer-local.json](https://github.com/greenpeace/planet4-test-pluto/blob/main/composer-local.json)

:watch: 2024.04.18 13:48:59

2024-04-22 13:55 UTC, mleray requested changes
I've filled up the Highlighted CTA on your example page, and I have similar feedback to what I said for the Deep Dive pattern: we are missing the necessary styles for the Image (rounded and no caption) and I still see the console warnings for the missing pattern category in the editor.
Also, looking at the [design system](https://p4-designsystem.greenpeace.org/05f6e9516/p/34f3b4-highlighted-cta) the text should be white and the button yellow? Something to double-check with the design team perhaps 🤔

2024-04-24 17:42 UTC, GP-Dan-Tovbein commented
> I've filled up the Highlighted CTA on your example page, and I have similar feedback to what I said for the Deep Dive pattern: we are missing the necessary styles for the Image (rounded and no caption) and I still see the console warnings for the missing pattern category in the editor. Also, looking at the [design system](https://p4-designsystem.greenpeace.org/05f6e9516/p/34f3b4-highlighted-cta) the text should be white and the button yellow? Something to double-check with the design team perhaps 🤔

@mleray the styling issue is fixed within [planet4-master-theme#2270](https://github.com/greenpeace/planet4-master-theme/pull/2270)

2024-04-29 13:00 UTC, GP-Dan-Tovbein commented
> I've filled up the Highlighted CTA on your example page, and I have similar feedback to what I said for the Deep Dive pattern: we are missing the necessary styles for the Image (rounded and no caption) and I still see the console warnings for the missing pattern category in the editor. Also, looking at the [design system](https://p4-designsystem.greenpeace.org/05f6e9516/p/34f3b4-highlighted-cta) the text should be white and the button yellow? Something to double-check with the design team perhaps 🤔

About the style, it's not working correctly even in production. Here is a [demo page](https://www-dev.greenpeace.org/international/suspendisse-eleifend-felis/).

2024-05-07 09:23 UTC, Osong-Michael reviewed
I am with @mleray on this maybe check with the design team to see which style to go with since it is different from that in the Design system. That way we just fix the styling issue at once.

2024-05-07 10:52 UTC, GP-Dan-Tovbein commented
@mleray @Osong-Michael I completely forgot to mention [this plugin's PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1205) which is in charge of refactoring the Highlighted CTA block.

2024-05-07 11:23 UTC, GP-Dan-Tovbein commented on assets/src/block-templates/highlighted-cta/template.js
> +import mainThemeUrl from '../main-theme-url';
Keep an eye this block's refactor, please!
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1205/files

2024-05-13 13:38 UTC, mleray commented
> About the style, it's not working correctly even in production. Here is a [demo page](https://www-dev.greenpeace.org/international/suspendisse-eleifend-felis/).

@GP-Dan-Tovbein I've made an error in my initial comment, the image in this case shouldn't be rounded. However it should be without caption and that's working in production but not on this [test page](https://www-dev.greenpeace.org/test-pluto/highlighted-cta/) for example! This isn't related to the stretched link since it isn't used here.

2024-05-14 13:54 UTC, GP-Dan-Tovbein commented
> > About the style, it's not working correctly even in production. Here is a [demo page](https://www-dev.greenpeace.org/international/suspendisse-eleifend-felis/).
> 
> @GP-Dan-Tovbein I've made an error in my initial comment, the image in this case shouldn't be rounded. However it should be without caption and that's working in production but not on this [test page](https://www-dev.greenpeace.org/test-pluto/highlighted-cta/) for example! This isn't related to the stretched link since it isn't used here.

Hey @mleray the issue about hiding captions is being applied within #2258.
I assume that once we merge that PR and rebase the current one, the issue is going to be automatically fixed.

2024-05-16 16:32 UTC, mleray approved these changes
Nice 👍

2024-05-16 16:33 UTC, merged