Add stretched link variations styles from plugin
greenpeace/planet4-master-theme pull request #2270
Opened 2024-04-24 15:46 UTC by GP-Dan-Tovbein

No ticket needed.

# Description
Required in master theme

2024-04-24 15:56 UTC, planet-4 commented
### Test instance is ready :rocket:

:new_moon: [venus](https://www-dev.greenpeace.org/test-venus) | [admin](https://www-dev.greenpeace.org/test-venus/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-venus/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-venus) | [composer-local.json](https://github.com/greenpeace/planet4-test-venus/blob/main/composer-local.json)

:watch: 2024.04.24 15:56:01

2024-04-25 08:29 UTC, mleray requested changes
We also need to [register the block variation in JS](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/e980c81583a3ffdf32ad86d718e0e6495caa1d9e/assets/src/editorIndex.js#L37-L50)

2024-04-25 10:28 UTC, GP-Dan-Tovbein commented on assets/src/block-variations/index.js
> + This file will register general block variations. In case of register a very
Added this legend

2024-04-25 11:42 UTC, mleray approved these changes
Tested on the instance, looks good to me 👍

2024-04-25 12:29 UTC, merged