PLANET-7576: Move `Planet4 blocks (beta)` category
greenpeace/planet4-master-theme pull request #2342
Opened 2024-08-06 12:24 UTC by GP-Dan-Tovbein

Ref: https://jira.greenpeace.org/browse/PLANET-7576

# Description
Move Planet4 beta blocks category from plugin to theme.

- This category should be added after we move blcosk from plugin to theme

2024-08-06 12:33 UTC, planet-4 commented
### Test instance is ready :rocket:

:new_moon: [pandora](https://www-dev.greenpeace.org/test-pandora) | [admin](https://www-dev.greenpeace.org/test-pandora/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-pandora/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-pandora) | [composer-local.json](https://github.com/greenpeace/planet4-test-pandora/blob/main/composer-local.json)

:watch: 2024.08.06 12:33:06

2024-08-09 11:58 UTC, mleray requested changes
I see that the Posts List and Actions List blocks still show when the beta blocks are deactivated, but they are not supposed to 🤔

2024-08-13 08:05 UTC, mleray commented
@GP-Dan-Tovbein should we also remove it from the plugin's repo? 🤔

2024-08-13 08:32 UTC, GP-Dan-Tovbein commented
> @GP-Dan-Tovbein should we also remove it from the plugin's repo? 🤔

I think yes, but also think it can be done in another ticket the current implementation is about to move it. I'll create a ticket for that

2024-08-14 08:34 UTC, mleray commented
Tested on the instance with different settings: 

**Beta blocks disabled and plugin deactivated:** all good 👍 

**Beta blocks enabled and plugin deactivated:**
- Posts List looks broken:  
<img width="766" alt="Screenshot 2024-08-14 at 10 27 50" src="https://github.com/user-attachments/assets/0aa01846-d7b1-4a95-aff2-048561d79c63">

- Actions List has an error because the Action Button Text block crashes

**Beta blocks disabled and plugin activated:** all good 👍 

**Beta blocks enabled and plugin activated:** Actions List has an error because the Action Button Text block crashes, Posts List looks good 👍

2024-08-14 08:54 UTC, mleray commented
> Actions List has an error because the Action Button Text block crashes

**Update:** the Action Button Text issue isn't related to your changes, I've opened a [small PR](https://github.com/greenpeace/planet4-master-theme/pull/2348) for a quick fix!

2024-08-14 09:30 UTC, mleray approved these changes
Turns out the Posts List issue isn't related to your changes, I've opened a [bug ticket](https://jira.greenpeace.org/browse/PLANET-7584) for it!
Looks good to me 👍

2024-08-14 09:40 UTC, GP-Dan-Tovbein commented
Thanks @mleray! Looking forward to your approval, then.

2024-08-14 09:40 UTC, merged