PLANET-7676 Added snippet for VWO Anti Flickering
greenpeace/planet4-master-theme pull request #2487
Opened 2024-12-19 11:19 UTC by Osong-Michael

- Added code to prevent flickering when A/B testing using VWO

### Summary

---

**Ref: https://jira.greenpeace.org/browse/PLANET-7676**

### Testing

1. When the _VWO A/B testing_ option is enabled in _Planet4_ > _Analytics_ the VWO script to prevent flickering during testing is added to the site. You can inspect the `head` tag to find the script.

2024-12-19 11:29 UTC, planet-4 commented
### Test instance is ready :rocket:

:new_moon: [telesto](https://www-dev.greenpeace.org/test-telesto) | [admin](https://www-dev.greenpeace.org/test-telesto/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-telesto/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-telesto) | [composer-local.json](https://github.com/greenpeace/planet4-test-telesto/blob/main/composer-local.json)

:watch: 2024.12.19 11:29:36

2025-01-21 16:24 UTC, sagarsdeshmukh submitted a review, later dismissed
PR looks good to me 👍

2025-03-26 09:15 UTC, comzeradd requested changes

2025-03-26 09:15 UTC, comzeradd commented on src/Settings.php
> +                    ],
Maybe we can have just this one setting. If it's empty, we do nothing. If there is an Account ID set here then we do both CSP and anti-flickering.

In that case we can use the `desc` text from the previous setting here to explain what will happen if they add the Accound ID. _"Adds a Content Security Policy exception for VWO and enables its anti-flicker mechanism."_

2025-03-26 09:15 UTC, comzeradd commented on templates/head/vwo_test_script.twig
> +<script type='text/javascript' id='vwoCode'>
Let's move the JS code out of the twig tempalte to be consistent with the @mardelnet's recent work at #2502

2025-03-28 16:09 UTC, comzeradd approved these changes

2025-03-28 16:09 UTC, comzeradd commented on assets/src/js/vwo_smart_code.js
> +    <link rel="preconnect" href="https://dev.visualwebsiteoptimizer.com" />
I know this is coming from VWO docs but maybe better to use `dns-prefetch` instead. It's a "cheaper" operation and it's consistent with what [we do already](https://github.com/greenpeace/planet4-master-theme/blob/4266c0e68b3dbcb15e027a46ef618581ce19a296/templates/html-header.twig#L40) with other services

2025-04-01 09:32 UTC, merged