PLANET-7511 Migrate Articles block to Posts List block
greenpeace/planet4-master-theme pull request #2491
Opened 2024-12-31 16:50 UTC by sagarsdeshmukh

Ref. https://jira.greenpeace.org/browse/PLANET-7511

### Summary

---

Ref: 

### Testing

1. 
2. 
3.

2024-12-31 16:59 UTC, planet-4 commented
### Test instance is ready :rocket:

:new_moon: [mars](https://www-dev.greenpeace.org/test-mars) | [admin](https://www-dev.greenpeace.org/test-mars/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-mars/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-mars) | [composer-local.json](https://github.com/greenpeace/planet4-test-mars/blob/main/composer-local.json)

:watch: 2024.12.31 16:59:04

2025-02-13 07:41 UTC, Osong-Michael requested changes

2025-02-13 07:41 UTC, Osong-Michael commented on src/Migrations/M040MigrateArticlesBlockToPostsListBlock.php
> +                                            ['term' => 'post_tag', 'separator' => ' ']
Hey @sagarsdeshmukh the _category_ comes before the _post-tag_

2025-02-13 07:41 UTC, Osong-Michael commented on src/Migrations/M040MigrateArticlesBlockToPostsListBlock.php
> +                                    ['className' => 'posts-list-meta']
This className is only for the div with the `author-name` and `post-date`

2025-02-19 08:50 UTC, Osong-Michael commented on src/Migrations/M040MigrateArticlesBlockToPostsListBlock.php
> +                                    Utils\Constants::BLOCK_TITLE
This Post title is a link

2025-02-24 11:15 UTC, sagarsdeshmukh commented on src/Migrations/M040MigrateArticlesBlockToPostsListBlock.php
> +                                    Utils\Constants::BLOCK_TITLE
Post title link updated. Please have a look.

2025-02-25 02:13 UTC, Osong-Michael submitted a review, later dismissed
👍 tested on local, works as expected

2025-02-25 08:27 UTC, mardelnet reviewed
@sagarsdeshmukh, shouldn't we remove the Articles block from the codebase, too?

2025-02-25 08:32 UTC, sagarsdeshmukh commented
> @sagarsdeshmukh, shouldn't we remove the Articles block from the codebase, too?

Yes, we should, but I’m waiting for confirmation on how to handle the 'Include Articles In Post' option if we remove the articles block. I’ve added a comment on [JIRA](https://jira.greenpeace.org/browse/PLANET-7511).

2025-02-25 08:50 UTC, mardelnet reviewed
Nice job @sagarsdeshmukh!
We also have to migrate the Additional CSS class(es).

2025-02-25 08:50 UTC, mardelnet commented on src/Migrations/Utils/Functions.php
I know you did not code this, but can you add an early return to the `create_block_paragraph` function?
The console shows a lot of warning messages because of the undefined array key `style`.

2025-02-25 09:01 UTC, mardelnet commented on src/Migrations/M042MigrateArticlesBlockToPostsListBlock.php
> +        $query['exclude'] = [];
What about using the `query['exclude']` attribute to exclude the current post, so we also avoid modifying the `process_blocks_recursive` function?

2025-02-26 04:28 UTC, sagarsdeshmukh commented on src/Migrations/M042MigrateArticlesBlockToPostsListBlock.php
> +        $query['exclude'] = [];
Could you please elaborate? 🤔 I’m already using `$query['exclude']` in the [code below](https://github.com/greenpeace/planet4-master-theme/pull/2491/files#diff-ea7744284c09ca548d83e9486ebe32f476c81fd10f904cc4ba9a16997afcafeeR161-R163). I'm not sure how we can avoid `process_blocks_recursive()`, as `current_post_id` needs to be passed from the [posts iteration loop](https://github.com/greenpeace/planet4-master-theme/blob/72e375d98845f775a71f2c38980cf315f0f0e7b2/src/Migrations/Utils/Functions.php#L44-L88).

2025-02-26 09:47 UTC, mardelnet reviewed
@sagarsdeshmukh, we also have to migrate the Additional CSS class(es):

![Edit-Page-‹-Greenpeace-—-WordPress](https://github.com/user-attachments/assets/504f6610-6cd5-45b7-a7cf-026c4a22312c)

2025-02-26 10:10 UTC, mardelnet commented on src/Migrations/Utils/Functions.php
> +                }
Maybe we can remove this condition as the previous one (`if ($block_check_callback($block))`) calls the `check_is_valid_block` function which returns only Article blocks (`return $block['blockName'] === Utils\Constants::BLOCK_ARTICLES;`)

2025-02-26 10:13 UTC, mardelnet commented on src/Migrations/M042MigrateArticlesBlockToPostsListBlock.php
> +        $query['exclude'] = [];
I see your point, thanks.
What if we remove the `if` condition you added to the `process_blocks_recursive` function and pass the post ID to all the targeted blocks? Would that hurt something?

2025-02-26 10:55 UTC, Osong-Michael commented
> @sagarsdeshmukh, we also have to migrate the Additional CSS class(es):
> 
> ![Edit-Page-‹-Greenpeace-—-WordPress](https://private-user-images.githubusercontent.com/59029273/417079914-504f6610-6cd5-45b7-a7cf-026c4a22312c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA1Njc1NTAsIm5iZiI6MTc0MDU2NzI1MCwicGF0aCI6Ii81OTAyOTI3My80MTcwNzk5MTQtNTA0ZjY2MTAtNmNkNS00NWI3LWE3Y2YtMDI2YzRhMjIzMTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjI2VDEwNTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NGQ5OTkxYWJiZGVmMjg2MmUxNTMxMzk2MDlmYTk2YmQ0OGUwN2VlNzMxMTQzY2UyYTk2MTg5Mzk5YmM3MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wBEa7C01xtSJA7LtDH7RLGokDzgsdtnC1y1gCSAF29k)

Those classes we already add [here](https://github.com/greenpeace/planet4-master-theme/blob/main/src/Migrations/Utils/Functions.php#L497), WP declares them as "Additional classes" since we added them during the block variation regsitration

2025-02-26 11:01 UTC, mardelnet commented
> > @sagarsdeshmukh, we also have to migrate the Additional CSS class(es):

> Those classes we already add [here](https://github.com/greenpeace/planet4-master-theme/blob/main/src/Migrations/Utils/Functions.php#L497), WP declares them as "Additional classes" since we added them during the block variation regsitration

Thanks @Osong-Michael 
Locally, when I add a new additional class to the Articles block, that class is not part of the Post List block after running the migration script.

2025-02-26 11:09 UTC, sagarsdeshmukh commented on src/Migrations/M042MigrateArticlesBlockToPostsListBlock.php
> +        $query['exclude'] = [];
No, it's not. Earlier, I was focused on the Articles Block use case. I've updated the PR

2025-04-03 10:01 UTC, sagarsdeshmukh commented
> @sagarsdeshmukh, we also have to migrate the Additional CSS class(es):
> 
> ![Edit-Page-‹-Greenpeace-—-WordPress](https://private-user-images.githubusercontent.com/59029273/417079914-504f6610-6cd5-45b7-a7cf-026c4a22312c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM2NzQ1NTMsIm5iZiI6MTc0MzY3NDI1MywicGF0aCI6Ii81OTAyOTI3My80MTcwNzk5MTQtNTA0ZjY2MTAtNmNkNS00NWI3LWE3Y2YtMDI2YzRhMjIzMTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDAzVDA5NTczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MWZlNDI2YzI3MzMyMzdmYTFmYjkxNGFjNzkxZjU1Yjk3NTJmY2ZiNDc2ZGU2MjEwZmQyZjc0OTVlMzRmYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2wrcUHi74Mk0FkfFqs2OiooakjRZbxOEmkG6v8gZykc)

Hi @mardelnet , Thank you for your feedback 🙏  I've updated the PR for 'Additional CSS class(es).' Please have a look when you get a chance.

2025-04-03 10:03 UTC, Osong-Michael commented on src/Migrations/M044MigrateArticlesBlockToPostsListBlock.php
> +            'rows' => isset($attrs['article_count']) ? $attrs['article_count'] : 3,
Sorry this is me being picky, but calling this "rows" is kinda confusing since this is the `article_count` for the _Articles block_ and `per_page` for Posts List and is the number of posts to display.

2025-04-03 10:12 UTC, Osong-Michael commented on src/Migrations/M044MigrateArticlesBlockToPostsListBlock.php
> +        $query['postType'] = Utils\Constants::POST_TYPES_POST;
I see in the Articles Block settings we have a Post Type setting, why don't we check if it contains a value before defaulting to this.

2025-04-03 12:41 UTC, mardelnet reviewed
@sagarsdeshmukh 
The `planet4-blocks/articles` block is still part of some templates (`homepage`, `take-action`, and others). Should we replace it?

2025-04-03 12:45 UTC, mardelnet reviewed
@sagarsdeshmukh 
There's also a mention of the `planet4-blocks/articles` block in the `assets/src/blocks/TableOfContents/getHeadingsFromBlocks.js` file.

2025-04-04 07:55 UTC, mardelnet commented on src/Migrations/M044MigrateArticlesBlockToPostsListBlock.php
> +                'url' => get_permalink(get_option('page_for_posts')),
Should we use here the values of "Button Text" and "Button Link"?

![image](https://github.com/user-attachments/assets/771daa22-a803-4e66-9d64-21de3d513d49)

2025-04-04 07:55 UTC, mardelnet commented on src/Migrations/M044MigrateArticlesBlockToPostsListBlock.php
> +     * Create and get a new group block for the Covers head.
This description is not accurate.

2025-04-04 07:55 UTC, mardelnet commented on src/Migrations/Utils/Functions.php
> +            'style="margin-top: ' . $margin['top'] . '; margin-bottom: ' . $margin['bottom'] . ';"' :
What if `$attrs['style']` exists but `$attrs['style']['spacing']['margin']` doesn't?

2025-04-09 10:40 UTC, sagarsdeshmukh commented on src/Migrations/M044MigrateArticlesBlockToPostsListBlock.php
> +        $query['postType'] = Utils\Constants::POST_TYPES_POST;
The articles block filters only `PostType Post` and not pages or actions, hence we have this value.

2025-04-09 10:45 UTC, sagarsdeshmukh commented on src/Migrations/M044MigrateArticlesBlockToPostsListBlock.php
> +                'url' => get_permalink(get_option('page_for_posts')),
I'm not sure about this change, as it won't be editable from the backend of the PostList block. 
cc: @comzeradd

2025-04-09 11:13 UTC, sagarsdeshmukh commented on src/Migrations/Utils/Functions.php
> +            'style="margin-top: ' . $margin['top'] . '; margin-bottom: ' . $margin['bottom'] . ';"' :
Good point, Condition updated!

2025-04-09 11:15 UTC, comzeradd commented on src/Migrations/M044MigrateArticlesBlockToPostsListBlock.php
> +                'url' => get_permalink(get_option('page_for_posts')),
Yeah, for now let's stick to the `page_for_posts` setting. There are some discussions with the design team to make that link more configurable in the future.

2025-04-15 10:58 UTC, sagarsdeshmukh commented
> @sagarsdeshmukh The `planet4-blocks/articles` block is still part of some templates (`homepage`, `take-action`, and others). Should we replace it?

Hi @mardelnet , Thank you for feedback. I updated the Block templates with Posts list block. could you please recheck the PR.

2025-04-15 11:12 UTC, mardelnet commented on assets/src/blocks/PostsList/index.js
@sagarsdeshmukh, can you please briefly explain why the changes in this file are necessary?

2025-04-15 11:22 UTC, sagarsdeshmukh commented on assets/src/blocks/PostsList/index.js
In the block-templates file — for example, the Homepage block template (assets/src/block-templates/homepage/template.js) — we need to pass the Posts List block attributes and Inner blocks as arguments to the Query Loop block. For instance:
```
['core/query',
  POSTS_LIST_BLOCK_ATTRIBUTES,
  getPostListBlockTemplate(__('Daily actions', 'planet4-blocks'))
]
```
To reuse the same Posts List block attributes configuration and Inner blocks structure, I’ve updated the Posts List block file accordingly.

2025-04-16 06:28 UTC, sagarsdeshmukh commented on assets/src/blocks/PostsList/index.js
Yes, that's correct.

2025-04-16 09:01 UTC, mardelnet reviewed
Your changes look good to me, @sagarsdeshmukh, well done!
I'll approve your PR once the failing frontend tests are fixed.
Maybe a second approval would be a good idea considering the impact of these changes, what do you think?

2025-04-18 05:54 UTC, sagarsdeshmukh commented
> Your changes look good to me, @sagarsdeshmukh, well done! I'll approve your PR once the failing frontend tests are fixed. Maybe a second approval would be a good idea considering the impact of these changes, what do you think?

Thanks, @mardelnet . The frontend tests have passed now. I agree with your points. Perhaps @Osong-Michael  , @mleray , or @GP-Dan-Tovbein could also take a look at this PR.

2025-04-21 09:10 UTC, mardelnet approved these changes

2025-04-21 20:32 UTC, Osong-Michael approved these changes
👍  Great job on this @sagarsdeshmukh

2025-04-25 13:32 UTC, sagarsdeshmukh commented
Hi @mardelnet , After merging the [PLANET-7791: Create url_passthrough setting #2600](https://github.com/greenpeace/planet4-master-theme/pull/2600) PR, the Articles migration PR had some code conflicts. I’ve resolved all the conflicts and rebased my PR.

Just to be sure everything looks good, could you please have a quick look at the updated PR?
(The major conflict was in the `assets/src/blocks/PostsList/index.js` file since we both worked on it.)

Thank you so much for your support and help in moving this PR forward! 🙂

2025-04-28 07:31 UTC, mardelnet commented on src/Migrations/M046MigrateArticlesBlockToPostsListBlock.php
> +                                    ],
@sagarsdeshmukh, according to PR #2594, the post terms blocks were replaced by the new `p4/taxonomy-breadcrumb` block.

2025-04-28 10:16 UTC, mardelnet commented on src/Migrations/M046MigrateArticlesBlockToPostsListBlock.php
> +                                    ],
I still see the post terms blocks. Have you pushed your changes, @sagarsdeshmukh?

2025-04-28 10:55 UTC, sagarsdeshmukh commented on src/Migrations/M046MigrateArticlesBlockToPostsListBlock.php
> +                                    ],
Could you please check now 🙏

2025-04-28 11:25 UTC, mardelnet commented on src/Migrations/M046MigrateArticlesBlockToPostsListBlock.php
> +                                    ],
Good job, @sagarsdeshmukh 
Your PR looks good to me.

2025-04-28 11:36 UTC, merged